#!/bin/bash

echo "======================================"
echo "Testing Blog Language Switching"
echo "======================================"
echo ""

echo "🔍 Checking database translations..."
echo ""

# Check if we can connect to database
if command -v psql &> /dev/null; then
  echo "Note: To check DB directly, run:"
  echo "  SELECT locale, slug, title, translation_group_id FROM blog_posts WHERE locale IN ('ru', 'en') AND published = true;"
else
  echo "✓ Database check skipped (manual verification needed)"
fi

echo ""
echo "======================================"
echo "Manual Testing Steps"
echo "======================================"
echo ""

echo "1️⃣  Start the dev server:"
echo "   npm run build && npm run preview"
echo ""

echo "2️⃣  Open browser with DevTools (F12) console open:"
echo "   http://localhost:4173/ru/blog/osveshchenie-detskoy-komnaty-indeks-tsvetoperedachi/"
echo ""

echo "3️⃣  Check console logs on page load:"
echo "   ✓ [BlogPost] Loading post: slug=\"osveshchenie-detskoy-komnaty-indeks-tsvetoperedachi\", locale=\"ru\""
echo "   ✓ [BlogPost] Post loaded successfully: Освещение детской комнаты..."
echo "   ✓ [BlogPost] Loading translations for group: 414465aa-..."
echo "   ✓ [BlogPost] Found translations: Array(2)"
echo "   ✓ [BlogPost] Setting translations: {en: \"...\", ru: \"...\"}"
echo ""

echo "4️⃣  Test RU → EN switching:"
echo "   a) Click language switcher (Globe icon)"
echo "   b) Select 'English'"
echo "   c) Check console logs:"
echo "      ✓ [LocaleSwitcher] Blog post detected, translations: {...}"
echo "      ✓ [LocaleSwitcher] Found translation for en: /en/blog/children-room-lighting-cri-color-rendering/"
echo "   d) Verify URL changed to: /en/blog/children-room-lighting-cri-color-rendering/"
echo "   e) Verify page shows English content"
echo ""

echo "5️⃣  Test EN → RU switching:"
echo "   a) Click language switcher"
echo "   b) Select 'Русский'"
echo "   c) Check console logs:"
echo "      ✓ [LocaleSwitcher] Found translation for ru: /ru/blog/osveshchenie-detskoy-komnaty-indeks-tsvetoperedachi/"
echo "   d) Verify URL changed back to: /ru/blog/osveshchenie-detskoy-komnaty-indeks-tsvetoperedachi/"
echo "   e) Verify page shows Russian content"
echo ""

echo "6️⃣  Test page refresh (NO redirect loop):"
echo "   a) On RU page, press F5 (refresh)"
echo "   b) Page should load RU content without URL change"
echo "   c) On EN page, press F5 (refresh)"
echo "   d) Page should load EN content without URL change"
echo "   e) NO flashing or automatic redirects"
echo ""

echo "7️⃣  Test hreflang tags:"
echo "   a) On RU page, View Page Source (Ctrl+U)"
echo "   b) Search for 'hreflang'"
echo "   c) Should find:"
echo "      <link rel=\"alternate\" hreflang=\"ru\" href=\"...ru/blog/osveshchenie-detskoy-komnaty-indeks-tsvetoperedachi/\" />"
echo "      <link rel=\"alternate\" hreflang=\"en\" href=\"...en/blog/children-room-lighting-cri-color-rendering/\" />"
echo ""

echo "======================================"
echo "Test Second Blog Post"
echo "======================================"
echo ""

echo "8️⃣  Test another post (verify consistency):"
echo "   RU: http://localhost:4173/ru/blog/zamena-lyustry-na-svetodiodnuyu-lentu/"
echo "   EN: http://localhost:4173/en/blog/can-led-strip-replace-chandelier/"
echo ""
echo "   Repeat steps 3-7 for this post"
echo ""

echo "======================================"
echo "Expected Results"
echo "======================================"
echo ""
echo "✅ RU post loads without redirect"
echo "✅ EN post loads without redirect"
echo "✅ RU → EN switches to correct EN slug"
echo "✅ EN → RU switches to correct RU slug"
echo "✅ F5 refresh keeps current locale"
echo "✅ No page flashing or loops"
echo "✅ hreflang tags present"
echo "✅ Console logs show translations loaded"
echo ""

echo "======================================"
echo "Troubleshooting"
echo "======================================"
echo ""
echo "❌ If translations are empty in console:"
echo "   - Check translation_group_id in database"
echo "   - Verify BlogTranslationsProvider in App.tsx"
echo "   - Check [BlogPost] logs for 'Setting translations'"
echo ""
echo "❌ If language switch shows 404:"
echo "   - Verify both posts are published (published = true)"
echo "   - Check slugs match in database"
echo "   - Check translation_group_id matches"
echo ""
echo "❌ If redirect loop occurs:"
echo "   - Check no navigate() in BlogPost useEffect"
echo "   - Verify loadPost doesn't redirect on 404"
echo "   - Check LocaleWrapper logic"
echo ""

echo "======================================"
echo "Quick Database Check"
echo "======================================"
echo ""
echo "Run this SQL to verify translations:"
echo ""
echo "SELECT locale, slug, title, translation_group_id, published"
echo "FROM blog_posts"
echo "WHERE translation_group_id = '414465aa-b3c2-4959-95e4-988930c90491'"
echo "ORDER BY locale;"
echo ""

echo "Expected: 2 rows (ru + en), both published = true"
echo ""

echo "======================================"
echo "Start Testing Now"
echo "======================================"
echo ""
echo "Run: npm run build && npm run preview"
echo "Then follow the steps above ^"
echo ""
