/*
  # Add cz, de, pl, uk translations for how-to-choose-led-strip-power-supply
*/

INSERT INTO blog_posts (slug, locale, title, excerpt, content, image_url, seo_title, seo_description, seo_keywords, published, published_at, translation_group_id)
VALUES
(
  'how-to-choose-led-strip-power-supply', 'cz',
  'Jak vybrat správný napájecí zdroj pro LED pásky',
  'Kompletní průvodce výběrem napájecího zdroje pro LED pásky. Výpočet výkonu, typy napájecích zdrojů, bezpečnostní rezervy a osvědčené postupy instalace.',
  E'# Jak vybrat správný napájecí zdroj pro LED pásky\n\nVýběr správného napájecího zdroje je jedním z nejkritičtějších rozhodnutí v každém projektu LED osvětlení. Nesprávná volba může vést ke stmívání, blikání, předčasnému selhání nebo dokonce k bezpečnostním rizikům. Tento komplexní průvodce vám pomůže vypočítat požadavky a vybrat perfektní napájecí zdroj.\n\n## Pochopení požadavků LED pásků na napájení\n\nLED pásky vyžadují napájení DC (stejnosměrný proud), typicky 12 V nebo 24 V. Napájecí zdroj převádí střídavé napájení ze zásuvky na vhodné stejnosměrné napětí.\n\n### Základy napětí\n\n**12 V LED pásky:**\n- Nejběžnější a nejdostupnější\n- Vhodné pro kratší úseky (do 5 metrů)\n- Standardní varianta pro obytné projekty\n\n**24 V LED pásky:**\n- Lepší pro delší úseky (do 10 metrů)\n- Menší pokles napětí na velké vzdálenosti\n- Preferovány pro profesionální a komerční instalace\n\n## Výpočet požadavků na výkon\n\n### Krok 1: Zjistěte spotřebu pásku\n\nLED pásky uvádějí spotřebu v wattech na metr (W/m):\n- Nízká hustota: 4,8–7,2 W/m\n- Vysoká hustota: 14,4–19,2 W/m\n- COB LED pásky: 10–20 W/m\n\n### Krok 2: Vypočítejte celkový výkon\n\n**Vzorec:**\nCelkový výkon (W) = W/m × délka (m)\n\n**Příklad:**\n- 14,4 W/m × 10 m = 144 W\n\n### Krok 3: Přidejte bezpečnostní rezervu\n\nVždy přidejte 20% bezpečnostní rezervu:\n- 144 W × 1,2 = 172,8 W\n- Zvolte napájecí zdroj 200 W\n\n## Typy napájecích zdrojů\n\n### Uzavřené napájecí zdroje\n\n**Vhodné pro:**\n- Obytné instalace\n- Projekty do 100 W\n- Viditelné instalace\n- Svépomocné projekty\n\n### Kovové skříňové napájecí zdroje\n\n**Vhodné pro:**\n- Komerční instalace\n- Projekty nad 100 W\n- Trvalé instalace\n\n### Vodotěsné napájecí zdroje\n\n**Vhodné pro:**\n- Venkovní instalace\n- Vlhká prostředí\n- Koupelny a kuchyně\n\n## Klíčové specifikace\n\n### Účinnost\n- 80 %: Základní napájecí zdroje\n- 85–90 %: Standardní kvalita\n- 90 %+: Prémiové napájecí zdroje\n\n### Bezpečnostní certifikace\n- CE (Evropa)\n- Zkratová ochrana\n- Ochrana proti přetížení\n- Tepelná ochrana\n\n## Kompatibilita stmívání\n\n**PWM stmívání:**\n- Nejběžnější pro LED pásky\n- Plynulý rozsah stmívání (0–100 %)\n- Nejlepší výkon\n\n**Doporučeno:** Standardní napájecí zdroj + samostatný LED regulátor pro nejlepší výsledky.\n\n## Časté chyby\n\n1. Nedostatečný výkon napájecího zdroje\n2. Nesprávné napětí\n3. Nedostatečné větrání\n4. Nesprávný průřez vodičů\n5. Ignorování IP krytí\n\n## Závěr\n\nVýběr správného napájecího zdroje je základem úspěchu LED osvětlení. Pečlivě vypočítejte požadavky, přidejte bezpečnostní rezervu a vyberte kvalitní komponenty.\n\n[Prohlédnout produktový katalog →](/cz/catalog)',
  'https://images.unsplash.com/photo-1593642532400-2682810df593?w=1200&auto=format&fit=crop',
  'Jak vybrat napájecí zdroj pro LED pásky: Kompletní průvodce',
  'Odborný průvodce výběrem napájecího zdroje pro LED pásky. Napětí, výpočet výkonu, bezpečnostní rezervy.',
  'napájecí zdroj LED pásku, napájení LED, napětí LED pásku, výpočet výkonu',
  true, '2025-07-07 21:00:00+00', '990fedeb-cdc4-4ddb-9497-3227eba9cec7'
),
(
  'how-to-choose-led-strip-power-supply', 'de',
  'Wie man das richtige Netzteil für LED-Streifen auswählt',
  'Vollständiger Leitfaden zur Auswahl des Netzteils für LED-Streifen. Leistungsberechnung, Netzteiltypen, Sicherheitsmargen und Best Practices für die Installation.',
  E'# Wie man das richtige Netzteil für LED-Streifen auswählt\n\nDie Wahl des richtigen Netzteils ist eine der kritischsten Entscheidungen bei jedem LED-Beleuchtungsprojekt. Eine falsche Wahl kann zu Verdunklung, Flackern, vorzeitigem Ausfall oder sogar Sicherheitsrisiken führen.\n\n## Grundlagen der LED-Streifen-Stromversorgung\n\nLED-Streifen benötigen DC-Strom (Gleichstrom), typischerweise 12 V oder 24 V.\n\n### Spannungsgrundlagen\n\n**12 V LED-Streifen:**\n- Am häufigsten verfügbar\n- Ideal für kürzere Abschnitte (bis 5 Meter)\n- Standardoption für Wohnprojekte\n\n**24 V LED-Streifen:**\n- Besser für längere Abschnitte (bis 10 Meter)\n- Weniger Spannungsabfall\n- Bevorzugt für professionelle Installationen\n\n## Leistungsberechnung\n\n### Schritt 1: Stromverbrauch des Streifens ermitteln\n\n- Geringe Dichte: 4,8–7,2 W/m\n- Hohe Dichte: 14,4–19,2 W/m\n- COB LED-Streifen: 10–20 W/m\n\n### Schritt 2: Gesamtleistung berechnen\n\n**Formel:** Gesamtwatt = W/m × Meter\n\n**Beispiel:** 14,4 × 10 = 144 Watt\n\n### Schritt 3: Sicherheitsmarge hinzufügen\n\n20% Sicherheitsmarge immer hinzufügen:\n- 144 × 1,2 = 172,8 W → 200 W Netzteil\n\n## Netzteiltypen\n\n### Geschlossene Netzteile\nFür Wohninstallationen, Projekte unter 100 W, sichtbare Installationen.\n\n### Metallgehäuse-Netzteile\nFür kommerzielle Installationen, Projekte über 100 W.\n\n### Wasserdichte Netzteile\nFür Außeninstallationen, feuchte Umgebungen.\n\n## Wichtige Spezifikationen\n\n### Wirkungsgrad\n- 80 %: Basis-Netzteile\n- 85–90 %: Standardqualität\n- 90 %+: Premium-Netzteile\n\n### Sicherheitszertifizierungen\nCE (Europa), Kurzschlussschutz, Überlastschutz, Thermoschutz.\n\n## Dimmkompatibilität\n\n**PWM-Dimmen:** Am häufigsten für LED-Streifen, gleichmäßiger Dimmbereich (0–100 %).\n\n## Häufige Fehler\n\n1. Netzteil unterdimensioniert\n2. Falsche Spannung\n3. Schlechte Belüftung\n4. Falscher Leitungsquerschnitt\n5. IP-Schutzart ignoriert\n\n## Fazit\n\nDie Wahl des richtigen Netzteils ist grundlegend für den Erfolg der LED-Beleuchtung. Berechnen Sie Ihre Anforderungen sorgfältig und wählen Sie Qualitätskomponenten.\n\n[Produktkatalog ansehen →](/de/catalog)',
  'https://images.unsplash.com/photo-1593642532400-2682810df593?w=1200&auto=format&fit=crop',
  'Netzteil für LED-Streifen auswählen: Vollständiger Leitfaden',
  'Expertenführer zur Auswahl des richtigen Netzteils für LED-Streifen. Spannung, Leistungsberechnung, Sicherheitsmargen.',
  'Netzteil LED-Streifen, LED Netzteil, LED Spannung, Leistungsberechnung',
  true, '2025-07-07 21:00:00+00', '990fedeb-cdc4-4ddb-9497-3227eba9cec7'
),
(
  'how-to-choose-led-strip-power-supply', 'pl',
  'Jak wybrać odpowiedni zasilacz do taśm LED',
  'Kompletny przewodnik po wyborze zasilacza do taśm LED. Obliczanie mocy, typy zasilaczy, marginesy bezpieczeństwa i najlepsze praktyki instalacji.',
  E'# Jak wybrać odpowiedni zasilacz do taśm LED\n\nWybór właściwego zasilacza jest jedną z najważniejszych decyzji w każdym projekcie oświetlenia LED. Zły wybór może prowadzić do przyciemniania, migotania, przedwczesnej awarii lub zagrożeń bezpieczeństwa.\n\n## Podstawy zasilania taśm LED\n\nTaśmy LED wymagają zasilania DC (prąd stały), zazwyczaj 12 V lub 24 V.\n\n### Podstawy napięcia\n\n**Taśmy LED 12 V:**\n- Najczęstszy i najszerzej dostępny\n- Idealny dla krótszych odcinków (do 5 metrów)\n- Opcja standardowa dla projektów mieszkaniowych\n\n**Taśmy LED 24 V:**\n- Lepszy dla dłuższych odcinków (do 10 metrów)\n- Mniejszy spadek napięcia\n- Preferowany dla instalacji profesjonalnych\n\n## Obliczanie wymagań mocy\n\n### Krok 1: Ustal pobór mocy taśmy\n\n- Niska gęstość: 4,8–7,2 W/m\n- Wysoka gęstość: 14,4–19,2 W/m\n- Taśmy COB LED: 10–20 W/m\n\n### Krok 2: Oblicz całkowitą moc\n\n**Wzór:** Łączne waty = W/m × metry\n\n**Przykład:** 14,4 × 10 = 144 W\n\n### Krok 3: Dodaj margines bezpieczeństwa\n\nZawsze dodaj 20% margines bezpieczeństwa:\n- 144 × 1,2 = 172,8 W → zasilacz 200 W\n\n## Typy zasilaczy\n\n### Zamknięte zasilacze\nDo instalacji mieszkaniowych, projektów poniżej 100 W.\n\n### Zasilacze w metalowej obudowie\nDo instalacji komercyjnych, projektów powyżej 100 W.\n\n### Wodoodporne zasilacze\nDo instalacji zewnętrznych, wilgotnych środowisk.\n\n## Kluczowe specyfikacje\n\n### Sprawność\n- 80 %: Zasilacze podstawowe\n- 85–90 %: Standardowa jakość\n- 90 %+: Zasilacze premium\n\n### Certyfikaty bezpieczeństwa\nCE (Europa), ochrona zwarciowa, ochrona przeciążeniowa, ochrona termiczna.\n\n## Zgodność z ściemnianiem\n\n**Ściemnianie PWM:** Najczęstsze dla taśm LED, płynny zakres ściemniania (0–100 %).\n\n## Częste błędy\n\n1. Niedostateczna moc zasilacza\n2. Błędne napięcie\n3. Zła wentylacja\n4. Nieprawidłowy przekrój przewodów\n5. Zignorowanie klasy IP\n\n## Podsumowanie\n\nWybór właściwego zasilacza jest fundamentem sukcesu oświetlenia LED. Dokładnie oblicz swoje wymagania i wybierz komponenty wysokiej jakości.\n\n[Zobacz katalog produktów →](/pl/catalog)',
  'https://images.unsplash.com/photo-1593642532400-2682810df593?w=1200&auto=format&fit=crop',
  'Jak wybrać zasilacz do taśm LED: Kompletny przewodnik',
  'Ekspercki przewodnik po wyborze zasilacza do taśm LED. Napięcie, obliczanie mocy, marginesy bezpieczeństwa.',
  'zasilacz do taśm LED, zasilanie LED, napięcie taśmy LED, obliczanie mocy',
  true, '2025-07-07 21:00:00+00', '990fedeb-cdc4-4ddb-9497-3227eba9cec7'
),
(
  'how-to-choose-led-strip-power-supply', 'uk',
  'Як вибрати правильний блок живлення для LED-стрічок',
  'Повний посібник з вибору блока живлення для LED-стрічок. Розрахунок потужності, типи блоків живлення, запаси безпеки та кращі практики монтажу.',
  E'# Як вибрати правильний блок живлення для LED-стрічок\n\nВибір правильного блока живлення — одне з найважливіших рішень у будь-якому проекті LED-освітлення. Неправильний вибір може призвести до затемнення, мерехтіння, передчасного виходу з ладу або навіть проблем з безпекою.\n\n## Основи живлення LED-стрічок\n\nLED-стрічки потребують постійного струму (DC), зазвичай 12 В або 24 В.\n\n### Основи напруги\n\n**LED-стрічки 12 В:**\n- Найбільш поширені\n- Ідеальні для коротких ділянок (до 5 метрів)\n- Стандартний варіант для житлових проектів\n\n**LED-стрічки 24 В:**\n- Кращі для довгих ділянок (до 10 метрів)\n- Менше падіння напруги\n- Переважні для професійних монтажів\n\n## Розрахунок вимог до потужності\n\n### Крок 1: Визначте споживання стрічки\n\n- Низька щільність: 4,8–7,2 Вт/м\n- Висока щільність: 14,4–19,2 Вт/м\n- COB LED-стрічки: 10–20 Вт/м\n\n### Крок 2: Розрахуйте загальну потужність\n\n**Формула:** Загальні вати = Вт/м × метри\n\n**Приклад:** 14,4 × 10 = 144 Вт\n\n### Крок 3: Додайте запас безпеки\n\nЗавжди додавайте 20% запас безпеки:\n- 144 × 1,2 = 172,8 Вт → блок живлення 200 Вт\n\n## Типи блоків живлення\n\n### Закриті блоки живлення\nДля житлових монтажів, проектів до 100 Вт.\n\n### Блоки живлення в металевому корпусі\nДля комерційних монтажів, проектів понад 100 Вт.\n\n### Вологозахищені блоки живлення\nДля зовнішніх монтажів, вологих середовищ.\n\n## Ключові характеристики\n\n### ККД\n- 80 %: Базові блоки живлення\n- 85–90 %: Стандартна якість\n- 90 %+: Преміум-блоки живлення\n\n### Сертифікати безпеки\nCE (Європа), захист від короткого замикання, захист від перевантаження, тепловий захист.\n\n## Сумісність із диммером\n\n**ШІМ-диммування:** Найбільш поширене для LED-стрічок, плавний діапазон (0–100 %).\n\n## Часті помилки\n\n1. Недостатня потужність блока живлення\n2. Неправильна напруга\n3. Погана вентиляція\n4. Неправильний переріз проводів\n5. Ігнорування ступеня захисту IP\n\n## Висновок\n\nВибір правильного блока живлення є основою успіху LED-освітлення. Ретельно розрахуйте вимоги та оберіть якісні компоненти.\n\n[Переглянути каталог продуктів →](/uk/catalog)',
  'https://images.unsplash.com/photo-1593642532400-2682810df593?w=1200&auto=format&fit=crop',
  'Як вибрати блок живлення для LED-стрічок: Повний посібник',
  'Посібник з вибору блока живлення для LED-стрічок. Напруга, розрахунок потужності, запаси безпеки.',
  'блок живлення LED-стрічки, живлення LED, напруга LED, розрахунок потужності',
  true, '2025-07-07 21:00:00+00', '990fedeb-cdc4-4ddb-9497-3227eba9cec7'
);
